### ISSUE TITLE
[UI-Bug]: Rank graph not updating after switching to own profile

### ISSUE THREAD

**Issue by krefang** [ScoreSaber/ScoreSaber-Frontend#27]
After looking at someone else's profile on scoresaber, and then switching to your profile by clicking on the avatar > My profile, the rank graph does not update. Reloading the page fixes the bug
![image](https://user-images.githubusercontent.com/74023957/142877805-0845c4ff-3ae2-42c1-83a3-df085e7e0dd0.png)
![image](https://user-images.githubusercontent.com/74023957/142877975-75045db4-eb08-4f7e-81c2-e1855022ea62.png)

**Comment by JiveOff** [comment]
Fixed in #28, thank you @motzel 😊

**Comment by JiveOff** [comment]
Also, please note that deployment to the main website may take a few hours since Umby has to do it manually.

**Comment by krefang** [comment]
> Also, please note that deployment to the main website may take a few hours since Umby has to do it manually.

It seems that the fix has been deployed already, since the issue doesn't appear anymore for me
