### ISSUE TITLE
[API bug] Leaderboards totalCount varies from page to page

### ISSUE THREAD

**Issue by motzel** [ScoreSaber/ScoreSaber-Frontend#32]
https://scoresaber.com/api/leaderboards?page=2

![image](https://user-images.githubusercontent.com/1758707/142935956-e66221ec-aec6-4395-a931-4197f11e1ca6.png)

https://scoresaber.com/api/leaderboards?page=3

![image](https://user-images.githubusercontent.com/1758707/142935976-5e305361-9ee8-4db7-ae48-d5287dbf7cd5.png)

**Comment by Umbranoxio** [comment]
This is to do in with caching, as you move further through the pages you'll likely receive a more up-to-date cache, I don't see this as an issue.

**Comment by motzel** [comment]
Ok. I noticed this because when I clicked through the pages I was shown a different number of pages and I was wondering what was going on

![image](https://user-images.githubusercontent.com/1758707/143735747-201449e1-efaf-4dd7-bb1d-05aa1d6f42e1.png)
![image](https://user-images.githubusercontent.com/1758707/143735750-3dafdf03-e4b9-4252-bdc1-6fe3f595a0a9.png)

**Comment by motzel** [comment]
Issue to close
