### ISSUE TITLE
[UI-Bug] difficulties on leaderboard duplicated

### ISSUE THREAD

**Issue by zivoy** [ScoreSaber/ScoreSaber-Frontend#38]
The diffs on some leaderboards are showing up more than once
On [Mr. Blue Sky](https://scoresaber.com/leaderboard/80648) I'm counting 3 Normals, 5 Hards and 9 Experts

![image](https://user-images.githubusercontent.com/16857861/143072344-30868669-bc3f-4506-ae1a-143241b1b906.png)

**Comment by motzel** [comment]
These are not duplicates, but different leaderboards. Probably Standard, Lawless, 360 etc. But yeah, it should be grouped by type somehow.

**Comment by zivoy** [comment]
That map predates the 360 gamemode by quite a bit (it's from 2018). Also, when I select one of the diffs, say hard, it shows all 5 of them selected.

also there are only 3 diffs on this map in the standered gamemode and no others

**Comment by motzel** [comment]
Oh, each of these difficulties has a different leaderboardId so I assumed they were just different diff types. So this is probably a DB issue.

**Comment by wolfcomp** [comment]
From what is gotten in the api you can see they have different `_{Difficulty}_Standard{Gamemodifier}` endings, so this might be something that the game is doing on upload that makes it add more leaderboards

**Comment by wolfcomp** [comment]
As seen by this 
![image](https://user-images.githubusercontent.com/4028289/143202522-da3d70e4-8837-4044-be3e-e69dbdbea6a4.png)

**Comment by Umbranoxio** [comment]
Fixed 6268c030d6b70c8e671dc2df3e35aef690739c38
