### ISSUE TITLE
Player stats

### ISSUE THREAD

**Issue by motzel** [ScoreSaber/ScoreSaber-Frontend#42]
What is the reason for limiting the width of the player stats container to 500px?

![image](https://user-images.githubusercontent.com/1758707/143397803-577a1965-8ddf-44ef-9b03-a62893a3ad6a.png)

IMO, freeing up the width looks not only more compact, but simply better. Additionally, I would group the stats by type, exposing the most important ones first. Something like this:

![image](https://user-images.githubusercontent.com/1758707/143397833-9909615e-956c-4127-9362-2073a124863a.png)

Should I make a proper PR, or should it stay as it is now?

**Comment by Umbranoxio** [comment]
Go ahead and make a PR for this
