### ISSUE TITLE
CSS bug: columns clipping

### ISSUE THREAD

**Issue by Nyrio** [ScoreSaber/ScoreSaber-Frontend#54]
This is how the front page displays for me (Firefox on W10, 1080p 24'' screen):

![brilliant_css_b](https://user-images.githubusercontent.com/17441062/144416404-27583694-bf5e-44af-a2e6-2a6ffb1c1938.PNG)

**Comment by byhemechi** [comment]
This is expected behaviour

**Comment by Nyrio** [comment]
With the main content of the page taking only 1/3rd of the width, there are many ways to avoid clipping important information (and it's annoying having to scroll down to get to the horizontal scrollbar and see those columns).

Possible solutions would be:
- Making the table wider
- Gaining space by compressing the text of the 1st column to "1w" / "3m", or "90d"
- Putting the song artist on the mapper line instead of the title line
- Putting a max-width on that middle column
- Shifting the number of plays to the left so the title / artist column clips

**Comment by JiveOff** [comment]
![image](https://user-images.githubusercontent.com/24374817/144709083-88eee87c-048b-4dd8-bcd1-66e47b3abda9.png)
Working on this layout, do you have any other ideas?

**Comment by Nyrio** [comment]
@JiveOff I like how this looks, yes. Is the first column clipping if the song/artist names are too long, or will it possibly hide the other two columns again?

**Comment by JiveOff** [comment]
The song names get clipped if they reach a certain character limit. Not sure about the artist names though. I will give it a look.

**Comment by JiveOff** [comment]
![image](https://user-images.githubusercontent.com/24374817/144768853-f8718e62-4279-4205-be54-49bc67894cd6.png)

Should be better now, creating a PR. 😊

**Comment by Nyrio** [comment]
Great, thanks for the work on this!
