### ISSUE TITLE
Scores failing to upload recently

### ISSUE THREAD

**Issue by ShadowR1ft** [ScoreSaber/ScoreSaber-Frontend#69]
So this has been happening recently. Whenever I beat a song, I notice that above the ScoreSaber leaderboard, it says that my score failed to upload. I tried uninstalling ScoreSaber and reinstalling it through Mod Assistant, but that didn't work. I have no idea what's happening. Any help is appreciated. 

Also if this GitHub page is for developers, then please tell me so I don't bother anyone.

**Comment by eZconfirmed** [comment]
ScoreSaber has not been whitelisted for version 1.19.1, as there are several bugs that impact proper score submission. Please downgrade to an older version or wait for the next game update.

**Comment by ShadowR1ft** [comment]
Ok. Thank you. I think I'll wait for the next update as I don't want to have to go through the trouble of downgrading.
