### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by z3t4m4n** [ScoreSaber/ScoreSaber-Frontend#80]
Hi, 
When I open BS and select a custom level I see the following on the scoreboard:
"Failed to authenticate with scoresaber! Please restart your game" 
I've restarted the game several times, validated it, uninstalled all the mods, run BS, install just the essential mods for scoresaber, no joy.
I see the following on the logs:
```
[DEBUG @ 21:35:53 | ScoreSaber] Signing into ScoreSaber...
[ERROR @ 21:35:54 | ScoreSaber] Failed user authentication: Exception of type '#=znWVbbj8I0237C7iWHHW3$1Q=' was thrown.
[DEBUG @ 21:35:54 | ScoreSaber] Failed, attempting again (1 of 3 tries...)
[ERROR @ 21:35:58 | ScoreSaber] Failed user authentication: Exception of type '#=znWVbbj8I0237C7iWHHW3$1Q=' was thrown.
[DEBUG @ 21:35:58 | ScoreSaber] Failed, attempting again (2 of 3 tries...)
[ERROR @ 21:36:02 | ScoreSaber] Failed user authentication: Exception of type '#=znWVbbj8I0237C7iWHHW3$1Q=' was thrown.
[DEBUG @ 21:36:02 | ScoreSaber] Failed, attempting again (3 of 3 tries...)
[DEBUG @ 21:36:06 | ScoreSaber] Failed to authenticate with ScoreSaber! Please restart your game
```

Thanks.

**Comment by z3t4m4n** [comment]
[2022.11.14.21.35.36.log](https://github.com/ScoreSaber/ScoreSaber-Frontend/files/10006903/2022.11.14.21.35.36.log)

**Comment by MagnusWestin** [comment]
I have the same issue, but also for the official levels.

```
[DEBUG @ 16:33:04 | ScoreSaber] Signing into ScoreSaber...
[ERROR @ 16:33:04 | ScoreSaber] Failed user authentication: Exception of type '#=znWVbbj8I0237C7iWHHW3$1Q=' was thrown.
[DEBUG @ 16:33:04 | ScoreSaber] Failed, attempting again (1 of 3 tries...)
[ERROR @ 16:33:09 | ScoreSaber] Failed user authentication: Exception of type '#=znWVbbj8I0237C7iWHHW3$1Q=' was thrown.
[DEBUG @ 16:33:09 | ScoreSaber] Failed, attempting again (2 of 3 tries...)
[ERROR @ 16:33:13 | ScoreSaber] Failed user authentication: Exception of type '#=znWVbbj8I0237C7iWHHW3$1Q=' was thrown.
[DEBUG @ 16:33:13 | ScoreSaber] Failed, attempting again (3 of 3 tries...)
[DEBUG @ 16:33:17 | ScoreSaber] Failed to authenticate with ScoreSaber! Please restart your game
```

**Comment by z3t4m4n** [comment]
Today had more time. I renamed BS folder, reinstalled it from scratch, started it once, installed BSIPA soncore scoresaber and rest sugested mods using mod assistant, copied custom songs. Still same error on the leaderboard.

**Comment by ledona** [comment]
Have you by chance purchased all DLC content for the game? If so I'm guessing that's the problem. Same thing applies to BeatSaverVoting and BeatLeader. Something to do with the Auth token.

**Comment by z3t4m4n** [comment]
> Have you by chance purchased all DLC content for the game? If so I'm guessing that's the problem. Same thing applies to BeatSaverVoting and BeatLeader. Something to do with the Auth token.
Yes, I have all the DLCs.

**Comment by MagnusWestin** [comment]
yeah, same for me. Any way to fix it?

**Comment by z3t4m4n** [comment]
I've opened the issue [here](https://github.com/ScoreSaber/ScoreSaber-Plugin/issues/3), probably a more proper place.
